// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvIDtx5vWjtXj1qC8_f16iGrSTKwTFugw',
    appId: '1:637517842579:web:690ed3b6526eb50d78e566',
    messagingSenderId: '637517842579',
    projectId: 'ahmadtechdevweb',
    authDomain: 'ahmadtechdevweb.firebaseapp.com',
    storageBucket: 'ahmadtechdevweb.firebasestorage.app',
    measurementId: 'G-K6C7ZL2XW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNoxOJXR1BospW5qAyu9x9fIzMKY1-O2Y',
    appId: '1:637517842579:android:95df6ce32b6ec21c78e566',
    messagingSenderId: '637517842579',
    projectId: 'ahmadtechdevweb',
    storageBucket: 'ahmadtechdevweb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHg15lviWZfcahJiMhRlOazR8M-HPw7Po',
    appId: '1:637517842579:ios:6bcf429071d0019878e566',
    messagingSenderId: '637517842579',
    projectId: 'ahmadtechdevweb',
    storageBucket: 'ahmadtechdevweb.firebasestorage.app',
    iosBundleId: 'com.hmz.folio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9axcJh0MHZbkn3MqQH3KyBSueDqj1eEo',
    appId: '1:637517842579:web:535c72045d1c8ce778e566',
    messagingSenderId: '637517842579',
    projectId: 'ahmadtechdevweb',
    authDomain: 'ahmadtechdevweb.firebaseapp.com',
    storageBucket: 'ahmadtechdevweb.firebasestorage.app',
    measurementId: 'G-53X5LPV2W1',
  );
}
